# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev123+gd231661.d20230306'
__version_tuple__ = version_tuple = (0, 1, 'dev123', 'gd231661.d20230306')
